import ContactCard from 'components/private/chat/left-sidebar/components/ContactCard';

export default () => {
    const onContactClick = () => {
    };

    return (
        <div className="w-full h-full overflow-x-hidden overflow-y-auto">
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
            <ContactCard
                id={1}
                text="Maximiliano"
                imageUrl="src/assets/images/maximiliano.png"
                onClick={onContactClick}
            />
        </div>
    )
};